name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: bash
        condarc: |
          channels:
            - conda-forge
          channel_priority: strict
        cache-environment: true

    - name: Install package (editable)
      shell: bash -l {0}
      run: |
        micromamba run -n WBTSdata python -m pip install --upgrade pip
        micromamba run -n WBTSdata python -m pip install -e . --no-deps --force-reinstall

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        micromamba run -n WBTSdata jupyter nbconvert --to notebook --execute notebooks/demo.ipynb --output=demo-output.ipynb --ExecutePreprocessor.allow_errors=True
        mv notebooks/*output.ipynb docs/source/
        pushd docs
        micromamba run -n WBTSdata make clean html
        popd

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html